export async function up(knex) {
  await knex.raw(`
    CREATE TABLE users (
      user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      sso_id VARCHAR(100) UNIQUE,
      full_name VARCHAR(100) NOT NULL,
      email VARCHAR(150) UNIQUE NOT NULL,

      last_login TIMESTAMP NULL,

      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

      created_by BIGINT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_users_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id)
    );

    CREATE INDEX idx_users_email
      ON users(email);

    CREATE INDEX idx_users_active
      ON users(is_active);

    CREATE INDEX idx_users_deleted
      ON users(is_deleted);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS users CASCADE;
  `);
}
