/**
 * One row per user (unique on user_id) - overwritten in place on every
 * password set/change, not appended to. updated_by/updated_at record the
 * most recent change; created_by/created_at still record the original
 * password-set event (usually the user themself, or an Admin who
 * provisioned the account).
 */
export async function up(knex) {
  await knex.raw(`
    CREATE TABLE user_passwords (
      user_password_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      user_id BIGINT NOT NULL UNIQUE,
      hash_password VARCHAR(255) NOT NULL,

      created_by BIGINT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_user_password_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,

      CONSTRAINT fk_user_password_creator
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_user_password_updater
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
    );

    CREATE INDEX idx_user_password_user
      ON user_passwords(user_id);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS user_passwords CASCADE;
  `);
}
