export async function up(knex) {
  await knex.raw(`
    CREATE TABLE roles (
      role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      role_name VARCHAR(100) NOT NULL UNIQUE,
      role_level INTEGER NULL,
      description TEXT,

      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_roles_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_roles_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
    );
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS roles CASCADE;
  `);
}
