/**
 * One active role per user - unique on user_id alone (not user_id+role_id
 * like a history-preserving design would use). Changing a user's role is
 * an UPDATE of role_id on their single existing row, not an insert. This
 * trades away a full change-history in exchange for simplicity; updated_by
 * /updated_at at least capture who made the *most recent* change and when.
 */
export async function up(knex) {
  await knex.raw(`
    CREATE TABLE user_roles (
      user_roles_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      user_id BIGINT NOT NULL UNIQUE,
      role_id BIGINT NOT NULL,

      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

      assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      created_by BIGINT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,

      CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id),

      CONSTRAINT fk_user_roles_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_user_roles_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
    );

    CREATE INDEX idx_user_roles_user
      ON user_roles(user_id);

    CREATE INDEX idx_user_roles_role
      ON user_roles(role_id);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS user_roles CASCADE;
  `);
}
