/**
 * Changes from the original draft schema, per design discussion:
 *  - `title` renamed to `document_name` and made UNIQUE NOT NULL. A plain
 *    UNIQUE(title) could never coexist with the versioning design below,
 *    since an upgrade clones the same title into a brand-new document_id
 *    - a bare uniqueness constraint would reject that outright. The app
 *    layer composes document_name as "V{version_no} - {title}" before
 *    insert, so "V1 - Transformers" and "V2 - Transformers" are distinct
 *    unique strings for the same underlying title, while two unrelated
 *    new documents still can't both claim "V1 - Transformers". The
 *    original free-typed title is recovered when needed (edit-form
 *    pre-fill, composing the next version's name) by stripping the fixed
 *    "V{n} - " prefix, which is always system-generated, never user-typed.
 *  - `category` and `content` changed from nullable to NOT NULL - Doc
 *    Onboard requires both to create a document at all, so the schema now
 *    enforces what the flow already required.
 *  - `request_status` column intentionally does NOT exist here. documents
 *    is the single source of truth for `stage` only; "what phase/status is
 *    this document showing under right now" is always derived live from
 *    the latest row in whichever request table matches (see
 *    request.repository.js in each phase module) - a Rejected or
 *    Cancelled request is never bounced back to a lower phase, it stays
 *    visible at the phase it was rejected/cancelled, with a promote-again
 *    action right there.
 *  - parent_document_id / root_document_id support versioning via cloning
 *    with a *new* document_id per version (instead of reusing the same id
 *    and bumping version_no in place):
 *      parent_document_id -> the document this row was cloned from
 *                             (one hop back). NULL for an original v1.
 *      root_document_id   -> the original v1 of this document's family.
 *                             For v1 itself this equals its own
 *                             document_id (self-reference, set via an
 *                             UPDATE right after insert, since the id
 *                             isn't known until the row exists). Lets
 *                             "every version of this document" and
 *                             "current live version of this family" be
 *                             flat WHERE queries instead of a recursive
 *                             walk up parent_document_id.
 */
export async function up(knex) {
  await knex.raw(`
    CREATE TABLE documents (
      document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      category VARCHAR(100) NOT NULL,
      document_name VARCHAR(280) NOT NULL,
      content TEXT NOT NULL,

      version_no INTEGER NOT NULL DEFAULT 1,

      stage document_stage NOT NULL DEFAULT 'DRAFT',

      parent_document_id BIGINT NULL,
      root_document_id BIGINT NULL,

      is_locked BOOLEAN NOT NULL DEFAULT FALSE,
      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT uq_documents_document_name
        UNIQUE (document_name),

      CONSTRAINT fk_documents_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_documents_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_documents_parent
        FOREIGN KEY (parent_document_id)
        REFERENCES documents(document_id),

      CONSTRAINT fk_documents_root
        FOREIGN KEY (root_document_id)
        REFERENCES documents(document_id),

      CONSTRAINT chk_documents_version
        CHECK (version_no >= 1)
    );

    CREATE INDEX idx_documents_stage
      ON documents(stage);

    CREATE INDEX idx_documents_created_by
      ON documents(created_by);

    CREATE INDEX idx_documents_deleted
      ON documents(is_deleted);

    CREATE INDEX idx_documents_root
      ON documents(root_document_id);

    CREATE INDEX idx_documents_parent
      ON documents(parent_document_id);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS documents CASCADE;
  `);
}
