export async function up(knex) {
  await knex.raw(`
    CREATE TABLE document_stage_history (
      document_stage_history_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      document_id BIGINT NOT NULL,

      from_stage document_stage NOT NULL,
      to_stage document_stage NOT NULL,

      old_status request_status NULL,
      new_status request_status NOT NULL,

      action_by BIGINT NOT NULL,
      action_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_stage_history_document
        FOREIGN KEY (document_id)
        REFERENCES documents(document_id),

      CONSTRAINT fk_stage_history_action_by
        FOREIGN KEY (action_by)
        REFERENCES users(user_id)
    );

    CREATE INDEX idx_stage_history_document
      ON document_stage_history(document_id);

    CREATE INDEX idx_stage_history_action_at
      ON document_stage_history(action_at);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS document_stage_history CASCADE;
  `);
}
