/**
 * Changes from the original draft schema:
 *  - `title` renamed to `document_name`, matching the documents table.
 *  - root_document_id (denormalized copy of documents.root_document_id at
 *    publish time) so "give me the current public content for this
 *    document family" is a flat WHERE, no join back to documents needed.
 *  - is_current: when a new version completes Go-Live, its row is
 *    inserted with is_current=true and the previous current row for the
 *    same root_document_id is flipped to false, in the same transaction.
 *    This is also the flag the Home/Live feeds filter on so superseded
 *    versions never show up as separate rows.
 *  - uq_document_live_one_current_per_family: a PARTIAL unique index
 *    (only over rows where is_current = true) makes it structurally
 *    impossible for two versions of the same family to both be marked
 *    current, even if the app forgets to flip the old row - Postgres
 *    itself rejects the insert. (MySQL has no partial index - see the
 *    documented workaround in database/mysql/schema.sql.)
 *  - UNIQUE(document_id) is kept: a single document_id (one version) can
 *    still only ever be published once, since once LIVE it's locked.
 *  - is_current is also flipped to false, alongside is_deleted=true, when
 *    a live-deletion request is approved - both flags read the same way
 *    for "is this actually the live, visible doc" queries.
 */
export async function up(knex) {
  await knex.raw(`
    CREATE TABLE document_live (
      document_live_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      document_id BIGINT NOT NULL,
      root_document_id BIGINT NOT NULL,

      category VARCHAR(100) NOT NULL,
      document_name VARCHAR(280) NOT NULL,
      content TEXT NOT NULL,

      version_no INTEGER NOT NULL DEFAULT 1,

      is_current BOOLEAN NOT NULL DEFAULT TRUE,

      published_by BIGINT NOT NULL,
      published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

      CONSTRAINT uq_document_live_document
        UNIQUE (document_id),

      CONSTRAINT fk_document_live_document
        FOREIGN KEY (document_id)
        REFERENCES documents(document_id),

      CONSTRAINT fk_document_live_root
        FOREIGN KEY (root_document_id)
        REFERENCES documents(document_id),

      CONSTRAINT fk_document_live_published_by
        FOREIGN KEY (published_by)
        REFERENCES users(user_id)
    );

    CREATE INDEX idx_document_live_deleted
      ON document_live(is_deleted);

    CREATE INDEX idx_document_live_root
      ON document_live(root_document_id);

    CREATE UNIQUE INDEX uq_document_live_one_current_per_family
      ON document_live (root_document_id)
      WHERE is_current = true;
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS document_live CASCADE;
  `);
}
