/**
 * Every promote / re-promote raises a brand-new row here rather than
 * updating a previous rejected/cancelled one in place. This keeps a full,
 * append-only history of every attempt (matching document_stage_history's
 * pattern), and sidesteps the UNIQUE(editorial_request_id, approver_id)
 * constraint below - reusing an old row on retry would mean resetting a
 * previously-rejected approver's row back to PENDING, erasing the record
 * of their earlier decision. "Current status at this phase" is always the
 * latest row for a given document_id, ordered by created_at.
 */
export async function up(knex) {
  await knex.raw(`
    CREATE TABLE editorial_requests (
      editorial_request_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      document_id BIGINT NOT NULL,

      status request_status NOT NULL DEFAULT 'PENDING',

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_editorial_requests_document
        FOREIGN KEY (document_id)
        REFERENCES documents(document_id),

      CONSTRAINT fk_editorial_requests_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_editorial_requests_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
    );

    CREATE INDEX idx_editorial_requests_document
      ON editorial_requests(document_id);

    CREATE INDEX idx_editorial_requests_status
      ON editorial_requests(status);
  `);

  await knex.raw(`
    CREATE TABLE editorial_request_approvers (
      editorial_request_approvers_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      editorial_request_id BIGINT NOT NULL,
      approver_id BIGINT NOT NULL,

      approver_action approver_action NOT NULL DEFAULT 'PENDING',

      comments TEXT,

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_editorial_approvers_request
        FOREIGN KEY (editorial_request_id)
        REFERENCES editorial_requests(editorial_request_id)
        ON DELETE CASCADE,

      CONSTRAINT fk_editorial_approvers_user
        FOREIGN KEY (approver_id)
        REFERENCES users(user_id),

      CONSTRAINT fk_editorial_approvers_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_editorial_approvers_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id),

      CONSTRAINT uq_editorial_request_approver
        UNIQUE (editorial_request_id, approver_id)
    );

    CREATE INDEX idx_editorial_approvers_request
      ON editorial_request_approvers(editorial_request_id);

    CREATE INDEX idx_editorial_approvers_user
      ON editorial_request_approvers(approver_id);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS editorial_request_approvers CASCADE;
    DROP TABLE IF EXISTS editorial_requests CASCADE;
  `);
}
