export async function up(knex) {
  await knex.raw(`
    CREATE TABLE review_requests (
      review_request_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      document_id BIGINT NOT NULL,

      status request_status NOT NULL DEFAULT 'PENDING',

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_review_requests_document
        FOREIGN KEY (document_id)
        REFERENCES documents(document_id),

      CONSTRAINT fk_review_requests_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_review_requests_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
    );

    CREATE INDEX idx_review_requests_document
      ON review_requests(document_id);

    CREATE INDEX idx_review_requests_status
      ON review_requests(status);
  `);

  await knex.raw(`
    CREATE TABLE review_request_approvers (
      review_request_approvers_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      review_request_id BIGINT NOT NULL,
      approver_id BIGINT NOT NULL,

      approver_action approver_action NOT NULL DEFAULT 'PENDING',

      comments TEXT,

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_review_approvers_request
        FOREIGN KEY (review_request_id)
        REFERENCES review_requests(review_request_id)
        ON DELETE CASCADE,

      CONSTRAINT fk_review_approvers_user
        FOREIGN KEY (approver_id)
        REFERENCES users(user_id),

      CONSTRAINT fk_review_approvers_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_review_approvers_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id),

      CONSTRAINT uq_review_request_approver
        UNIQUE (review_request_id, approver_id)
    );

    CREATE INDEX idx_review_approvers_request
      ON review_request_approvers(review_request_id);

    CREATE INDEX idx_review_approvers_user
      ON review_request_approvers(approver_id);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS review_request_approvers CASCADE;
    DROP TABLE IF EXISTS review_requests CASCADE;
  `);
}
