/**
 * A publisher's action on a Pending row here is the terminal decision for
 * the whole document, not a step toward a separate "promote to live"
 * call: APPROVED means the service layer publishes immediately (documents
 * .stage -> LIVE, a document_live row is inserted) and REJECTED means
 * "unpublished" (stage stays PUBLICATION, eligible for the author to
 * raise a fresh publication_requests row - same insert-new-row pattern as
 * every other phase). There is no separate "unpublish an already-live
 * doc" action; Live -> not-Live only ever happens through the Deletion
 * flow (live_delete_requests), which is a different, stricter,
 * three-approver decision.
 */
export async function up(knex) {
  await knex.raw(`
    CREATE TABLE publication_requests (
      publication_request_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      document_id BIGINT NOT NULL,

      status request_status NOT NULL DEFAULT 'PENDING',

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_publication_requests_document
        FOREIGN KEY (document_id)
        REFERENCES documents(document_id),

      CONSTRAINT fk_publication_requests_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_publication_requests_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id)
    );

    CREATE INDEX idx_publication_requests_document
      ON publication_requests(document_id);

    CREATE INDEX idx_publication_requests_status
      ON publication_requests(status);
  `);

  await knex.raw(`
    CREATE TABLE publication_request_approvers (
      publication_request_approvers_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      publication_request_id BIGINT NOT NULL,
      approver_id BIGINT NOT NULL,

      approver_action approver_action NOT NULL DEFAULT 'PENDING',

      comments TEXT,

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_publication_approvers_request
        FOREIGN KEY (publication_request_id)
        REFERENCES publication_requests(publication_request_id)
        ON DELETE CASCADE,

      CONSTRAINT fk_publication_approvers_user
        FOREIGN KEY (approver_id)
        REFERENCES users(user_id),

      CONSTRAINT fk_publication_approvers_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_publication_approvers_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id),

      CONSTRAINT uq_publication_request_approver
        UNIQUE (publication_request_id, approver_id)
    );

    CREATE INDEX idx_publication_approvers_request
      ON publication_request_approvers(publication_request_id);

    CREATE INDEX idx_publication_approvers_user
      ON publication_request_approvers(approver_id);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS publication_request_approvers CASCADE;
    DROP TABLE IF EXISTS publication_requests CASCADE;
  `);
}
