export async function up(knex) {
  await knex.raw(`
    CREATE TABLE live_delete_requests (
      delete_request_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      document_id BIGINT NOT NULL,

      reason TEXT NOT NULL,

      status request_status NOT NULL DEFAULT 'PENDING',

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_delete_requests_document
        FOREIGN KEY (document_id)
        REFERENCES documents(document_id),

      CONSTRAINT fk_delete_requests_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_delete_requests_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id),

      CONSTRAINT chk_delete_reason
        CHECK (length(trim(reason)) > 0)
    );

    CREATE INDEX idx_delete_requests_document
      ON live_delete_requests(document_id);

    CREATE INDEX idx_delete_requests_status
      ON live_delete_requests(status);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS live_delete_requests CASCADE;
  `);
}
