/**
 * Exactly one editor, one reviewer, one publisher per delete request -
 * enforced by uq_delete_request_role (one row per role per request), on
 * top of uq_delete_request_user (one row per person per request). All
 * three must APPROVE for the deletion to execute; a single REJECTED
 * cancels the whole request immediately (status on live_delete_requests
 * flips to REJECTED) rather than waiting on the remaining two - the
 * author can then raise a brand-new request (new delete_request_id) if
 * they still want to pursue it.
 */
export async function up(knex) {
  await knex.raw(`
    CREATE TABLE live_delete_request_approvers (
      live_delete_request_approvers_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      delete_request_id BIGINT NOT NULL,

      approver_id BIGINT NOT NULL,
      approver_role delete_approver_role NOT NULL,

      approver_action approver_action NOT NULL DEFAULT 'PENDING',

      comments TEXT,

      created_by BIGINT NOT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      updated_by BIGINT NULL,
      updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_delete_approvers_request
        FOREIGN KEY (delete_request_id)
        REFERENCES live_delete_requests(delete_request_id)
        ON DELETE CASCADE,

      CONSTRAINT fk_delete_approvers_user
        FOREIGN KEY (approver_id)
        REFERENCES users(user_id),

      CONSTRAINT fk_delete_approvers_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id),

      CONSTRAINT fk_delete_approvers_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES users(user_id),

      CONSTRAINT uq_delete_request_role
        UNIQUE (delete_request_id, approver_role),

      CONSTRAINT uq_delete_request_user
        UNIQUE (delete_request_id, approver_id)
    );

    CREATE INDEX idx_delete_approvers_request
      ON live_delete_request_approvers(delete_request_id);

    CREATE INDEX idx_delete_approvers_user
      ON live_delete_request_approvers(approver_id);

    CREATE INDEX idx_delete_approvers_role
      ON live_delete_request_approvers(approver_role);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS live_delete_request_approvers CASCADE;
  `);
}
