export async function up(knex) {
  await knex.raw(`
    CREATE TABLE user_login_logs (
      user_login_logs_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      user_id BIGINT NOT NULL,

      login_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      login_status user_login_status NOT NULL DEFAULT 'SUCCESS',

      failure_reason TEXT,
      ip_address VARCHAR(45),

      created_by BIGINT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_login_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,

      CONSTRAINT fk_login_logs_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(user_id)
    );

    CREATE INDEX idx_login_logs_user
      ON user_login_logs(user_id);

    CREATE INDEX idx_login_logs_login_time
      ON user_login_logs(login_time);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS user_login_logs CASCADE;
  `);
}
