export async function up(knex) {
  await knex.raw(`
    CREATE TABLE refresh_tokens (
      refresh_tokens_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT NOT NULL,
      token_hash TEXT NOT NULL UNIQUE,
      expires_at TIMESTAMP NOT NULL,
      revoked_at TIMESTAMP NULL,
      replaced_by_hash TEXT NULL,
      user_agent TEXT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
    );

    CREATE INDEX idx_refresh_tokens_user_id
      ON refresh_tokens(user_id);

    CREATE INDEX idx_refresh_tokens_expires_at
      ON refresh_tokens(expires_at);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS refresh_tokens CASCADE;
  `);
}
