/**
 * Supports POST /auth/forgot-password + POST /auth/reset-password.
 * Mirrors refresh_tokens' shape on purpose: only a hash of the token is
 * ever stored (the raw token is emailed to the user and never persisted),
 * so a leaked database row alone can't be used to reset anyone's
 * password. used_at is set the moment a token is consumed, so a token is
 * valid only while used_at IS NULL AND expires_at > now(). The service
 * layer also invalidates (sets used_at) any other outstanding tokens for
 * the same user whenever one is issued or consumed, so at most one
 * request link is ever live at a time.
 */
export async function up(knex) {
  await knex.raw(`
    CREATE TABLE password_reset_tokens (
      password_reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      user_id BIGINT NOT NULL,
      token_hash TEXT NOT NULL UNIQUE,

      expires_at TIMESTAMP NOT NULL,
      used_at TIMESTAMP NULL,

      requested_ip VARCHAR(45),

      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_password_reset_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
    );

    CREATE INDEX idx_password_reset_tokens_user
      ON password_reset_tokens(user_id);

    CREATE INDEX idx_password_reset_tokens_expires_at
      ON password_reset_tokens(expires_at);
  `);
}

export async function down(knex) {
  await knex.raw(`
    DROP TABLE IF EXISTS password_reset_tokens CASCADE;
  `);
}
