-- =====================================================================
-- DocFlow - PostgreSQL schema (plain SQL)
--
-- This is the consolidated equivalent of running every file in
-- database/knex/migrations in order. Use this if you want to stand up
-- the database without going through knex at all (e.g. `psql -f`).
-- If you ARE using knex, run the migrations instead - don't run both.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------
CREATE TYPE user_login_status AS ENUM ('SUCCESS', 'FAILURE');

CREATE TYPE document_stage AS ENUM ('DRAFT', 'EDITORIAL', 'REVIEW', 'PUBLICATION', 'LIVE');

CREATE TYPE request_status AS ENUM ('NONE', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');

CREATE TYPE approver_action AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');

CREATE TYPE delete_approver_role AS ENUM ('EDITOR', 'REVIEWER', 'PUBLISHER');

-- ---------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------
CREATE TABLE users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sso_id VARCHAR(100) UNIQUE,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  last_login TIMESTAMP NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users(user_id)
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_active ON users(is_active);
CREATE INDEX idx_users_deleted ON users(is_deleted);

-- ---------------------------------------------------------------------
-- user_passwords (one row per user, overwritten in place on change)
-- ---------------------------------------------------------------------
CREATE TABLE user_passwords (
  user_password_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,
  hash_password VARCHAR(255) NOT NULL,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_password_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_user_password_creator FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_user_password_updater FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

CREATE INDEX idx_user_password_user ON user_passwords(user_id);

-- ---------------------------------------------------------------------
-- roles
-- ---------------------------------------------------------------------
CREATE TABLE roles (
  role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(100) NOT NULL UNIQUE,
  role_level INTEGER NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_roles_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_roles_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

-- ---------------------------------------------------------------------
-- user_roles (one active role per user)
-- ---------------------------------------------------------------------
CREATE TABLE user_roles (
  user_roles_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,
  role_id BIGINT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(role_id),
  CONSTRAINT fk_user_roles_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_user_roles_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

CREATE INDEX idx_user_roles_user ON user_roles(user_id);
CREATE INDEX idx_user_roles_role ON user_roles(role_id);

-- ---------------------------------------------------------------------
-- documents
-- document_name = "V{version_no} - {title}", enforced UNIQUE. See the
-- comment in database/knex/migrations/006_create_documents.js for why
-- a plain UNIQUE(title) can't coexist with clone-based versioning.
-- ---------------------------------------------------------------------
CREATE TABLE documents (
  document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category VARCHAR(100) NOT NULL,
  document_name VARCHAR(280) NOT NULL,
  content TEXT NOT NULL,
  version_no INTEGER NOT NULL DEFAULT 1,
  stage document_stage NOT NULL DEFAULT 'DRAFT',
  parent_document_id BIGINT NULL,
  root_document_id BIGINT NULL,
  is_locked BOOLEAN NOT NULL DEFAULT FALSE,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_documents_document_name UNIQUE (document_name),
  CONSTRAINT fk_documents_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_documents_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
  CONSTRAINT fk_documents_parent FOREIGN KEY (parent_document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_documents_root FOREIGN KEY (root_document_id) REFERENCES documents(document_id),
  CONSTRAINT chk_documents_version CHECK (version_no >= 1)
);

CREATE INDEX idx_documents_stage ON documents(stage);
CREATE INDEX idx_documents_created_by ON documents(created_by);
CREATE INDEX idx_documents_deleted ON documents(is_deleted);
CREATE INDEX idx_documents_root ON documents(root_document_id);
CREATE INDEX idx_documents_parent ON documents(parent_document_id);

-- ---------------------------------------------------------------------
-- document_stage_history (append-only audit trail)
-- ---------------------------------------------------------------------
CREATE TABLE document_stage_history (
  document_stage_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  from_stage document_stage NOT NULL,
  to_stage document_stage NOT NULL,
  old_status request_status NULL,
  new_status request_status NOT NULL,
  action_by BIGINT NOT NULL,
  action_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_stage_history_document FOREIGN KEY (document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_stage_history_action_by FOREIGN KEY (action_by) REFERENCES users(user_id)
);

CREATE INDEX idx_stage_history_document ON document_stage_history(document_id);
CREATE INDEX idx_stage_history_action_at ON document_stage_history(action_at);

-- ---------------------------------------------------------------------
-- document_live (one row per version ever published; is_current marks
-- which version of a family is the one currently visible)
-- ---------------------------------------------------------------------
CREATE TABLE document_live (
  document_live_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  root_document_id BIGINT NOT NULL,
  category VARCHAR(100) NOT NULL,
  document_name VARCHAR(280) NOT NULL,
  content TEXT NOT NULL,
  version_no INTEGER NOT NULL DEFAULT 1,
  is_current BOOLEAN NOT NULL DEFAULT TRUE,
  published_by BIGINT NOT NULL,
  published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT uq_document_live_document UNIQUE (document_id),
  CONSTRAINT fk_document_live_document FOREIGN KEY (document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_document_live_root FOREIGN KEY (root_document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_document_live_published_by FOREIGN KEY (published_by) REFERENCES users(user_id)
);

CREATE INDEX idx_document_live_deleted ON document_live(is_deleted);
CREATE INDEX idx_document_live_root ON document_live(root_document_id);

-- Partial unique index: structurally impossible for two versions of the
-- same family to both be "current", even if the app forgets to flip the
-- old row - Postgres itself rejects the insert.
CREATE UNIQUE INDEX uq_document_live_one_current_per_family
  ON document_live (root_document_id)
  WHERE is_current = true;

-- ---------------------------------------------------------------------
-- editorial_requests / editorial_request_approvers
-- ---------------------------------------------------------------------
CREATE TABLE editorial_requests (
  editorial_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  status request_status NOT NULL DEFAULT 'PENDING',
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_editorial_requests_document FOREIGN KEY (document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_editorial_requests_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_editorial_requests_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

CREATE INDEX idx_editorial_requests_document ON editorial_requests(document_id);
CREATE INDEX idx_editorial_requests_status ON editorial_requests(status);

CREATE TABLE editorial_request_approvers (
  editorial_request_approvers_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  editorial_request_id BIGINT NOT NULL,
  approver_id BIGINT NOT NULL,
  approver_action approver_action NOT NULL DEFAULT 'PENDING',
  comments TEXT,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_editorial_approvers_request FOREIGN KEY (editorial_request_id) REFERENCES editorial_requests(editorial_request_id) ON DELETE CASCADE,
  CONSTRAINT fk_editorial_approvers_user FOREIGN KEY (approver_id) REFERENCES users(user_id),
  CONSTRAINT fk_editorial_approvers_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_editorial_approvers_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
  CONSTRAINT uq_editorial_request_approver UNIQUE (editorial_request_id, approver_id)
);

CREATE INDEX idx_editorial_approvers_request ON editorial_request_approvers(editorial_request_id);
CREATE INDEX idx_editorial_approvers_user ON editorial_request_approvers(approver_id);

-- ---------------------------------------------------------------------
-- review_requests / review_request_approvers
-- ---------------------------------------------------------------------
CREATE TABLE review_requests (
  review_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  status request_status NOT NULL DEFAULT 'PENDING',
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_review_requests_document FOREIGN KEY (document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_review_requests_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_review_requests_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

CREATE INDEX idx_review_requests_document ON review_requests(document_id);
CREATE INDEX idx_review_requests_status ON review_requests(status);

CREATE TABLE review_request_approvers (
  review_request_approvers_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_request_id BIGINT NOT NULL,
  approver_id BIGINT NOT NULL,
  approver_action approver_action NOT NULL DEFAULT 'PENDING',
  comments TEXT,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_review_approvers_request FOREIGN KEY (review_request_id) REFERENCES review_requests(review_request_id) ON DELETE CASCADE,
  CONSTRAINT fk_review_approvers_user FOREIGN KEY (approver_id) REFERENCES users(user_id),
  CONSTRAINT fk_review_approvers_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_review_approvers_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
  CONSTRAINT uq_review_request_approver UNIQUE (review_request_id, approver_id)
);

CREATE INDEX idx_review_approvers_request ON review_request_approvers(review_request_id);
CREATE INDEX idx_review_approvers_user ON review_request_approvers(approver_id);

-- ---------------------------------------------------------------------
-- publication_requests / publication_request_approvers
-- A publisher's APPROVED here publishes immediately; REJECTED means
-- "unpublished", staying at PUBLICATION for the author to re-raise.
-- ---------------------------------------------------------------------
CREATE TABLE publication_requests (
  publication_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  status request_status NOT NULL DEFAULT 'PENDING',
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_publication_requests_document FOREIGN KEY (document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_publication_requests_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_publication_requests_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id)
);

CREATE INDEX idx_publication_requests_document ON publication_requests(document_id);
CREATE INDEX idx_publication_requests_status ON publication_requests(status);

CREATE TABLE publication_request_approvers (
  publication_request_approvers_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publication_request_id BIGINT NOT NULL,
  approver_id BIGINT NOT NULL,
  approver_action approver_action NOT NULL DEFAULT 'PENDING',
  comments TEXT,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_publication_approvers_request FOREIGN KEY (publication_request_id) REFERENCES publication_requests(publication_request_id) ON DELETE CASCADE,
  CONSTRAINT fk_publication_approvers_user FOREIGN KEY (approver_id) REFERENCES users(user_id),
  CONSTRAINT fk_publication_approvers_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_publication_approvers_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
  CONSTRAINT uq_publication_request_approver UNIQUE (publication_request_id, approver_id)
);

CREATE INDEX idx_publication_approvers_request ON publication_request_approvers(publication_request_id);
CREATE INDEX idx_publication_approvers_user ON publication_request_approvers(approver_id);

-- ---------------------------------------------------------------------
-- live_delete_requests / live_delete_request_approvers
-- Exactly 1 editor + 1 reviewer + 1 publisher; all three must APPROVE,
-- any single REJECTED cancels the whole request.
-- ---------------------------------------------------------------------
CREATE TABLE live_delete_requests (
  delete_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  status request_status NOT NULL DEFAULT 'PENDING',
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_delete_requests_document FOREIGN KEY (document_id) REFERENCES documents(document_id),
  CONSTRAINT fk_delete_requests_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_delete_requests_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
  CONSTRAINT chk_delete_reason CHECK (length(trim(reason)) > 0)
);

CREATE INDEX idx_delete_requests_document ON live_delete_requests(document_id);
CREATE INDEX idx_delete_requests_status ON live_delete_requests(status);

CREATE TABLE live_delete_request_approvers (
  live_delete_request_approvers_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delete_request_id BIGINT NOT NULL,
  approver_id BIGINT NOT NULL,
  approver_role delete_approver_role NOT NULL,
  approver_action approver_action NOT NULL DEFAULT 'PENDING',
  comments TEXT,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by BIGINT NULL,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_delete_approvers_request FOREIGN KEY (delete_request_id) REFERENCES live_delete_requests(delete_request_id) ON DELETE CASCADE,
  CONSTRAINT fk_delete_approvers_user FOREIGN KEY (approver_id) REFERENCES users(user_id),
  CONSTRAINT fk_delete_approvers_created_by FOREIGN KEY (created_by) REFERENCES users(user_id),
  CONSTRAINT fk_delete_approvers_updated_by FOREIGN KEY (updated_by) REFERENCES users(user_id),
  CONSTRAINT uq_delete_request_role UNIQUE (delete_request_id, approver_role),
  CONSTRAINT uq_delete_request_user UNIQUE (delete_request_id, approver_id)
);

CREATE INDEX idx_delete_approvers_request ON live_delete_request_approvers(delete_request_id);
CREATE INDEX idx_delete_approvers_user ON live_delete_request_approvers(approver_id);
CREATE INDEX idx_delete_approvers_role ON live_delete_request_approvers(approver_role);

-- ---------------------------------------------------------------------
-- user_login_logs
-- ---------------------------------------------------------------------
CREATE TABLE user_login_logs (
  user_login_logs_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  login_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  login_status user_login_status NOT NULL DEFAULT 'SUCCESS',
  failure_reason TEXT,
  ip_address VARCHAR(45),
  created_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_login_logs_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
  CONSTRAINT fk_login_logs_created_by FOREIGN KEY (created_by) REFERENCES users(user_id)
);

CREATE INDEX idx_login_logs_user ON user_login_logs(user_id);
CREATE INDEX idx_login_logs_login_time ON user_login_logs(login_time);

-- ---------------------------------------------------------------------
-- refresh_tokens
-- ---------------------------------------------------------------------
CREATE TABLE refresh_tokens (
  refresh_tokens_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  revoked_at TIMESTAMP NULL,
  replaced_by_hash TEXT NULL,
  user_agent TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens(expires_at);

-- ---------------------------------------------------------------------
-- password_reset_tokens
-- ---------------------------------------------------------------------
CREATE TABLE password_reset_tokens (
  password_reset_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP NULL,
  requested_ip VARCHAR(45),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens(user_id);
CREATE INDEX idx_password_reset_tokens_expires_at ON password_reset_tokens(expires_at);

-- ---------------------------------------------------------------------
-- Seed data: 5 fixed roles + one bootstrap admin + 4 demo users
-- (mirrors database/knex/seeds/001_roles_and_admin.js - see that file
-- for why the ordering below is the way it is, and change these
-- passwords immediately after first login)
-- ---------------------------------------------------------------------
INSERT INTO users (user_id, full_name, email, is_active, created_by)
  OVERRIDING SYSTEM VALUE
  VALUES (1, 'Aditi Singh', 'aditi.singh@docflow.admin', true, NULL);

-- bcrypt hash (cost 12) of the placeholder password "password" - CHANGE THIS.
INSERT INTO user_passwords (user_id, hash_password, created_by)
  VALUES (1, '$2b$12$dhlUQj.V2qv48y9VymqSaeMq76QgXwstDl5/DPv/FCce.sd23bx7q', 1);

INSERT INTO roles (role_id, role_name, role_level, description, created_by)
  OVERRIDING SYSTEM VALUE
  VALUES
    (1, 'author', 1, 'Creates documents; the default role for every new registration.', 1),
    (2, 'editor', 2, 'Reviews documents promoted out of Draft, at the Editorial stage.', 1),
    (3, 'reviewer', 3, 'Confirms documents promoted out of Editorial, at the Review stage.', 1),
    (4, 'publisher', 4, 'Publishes or unpublishes documents promoted out of Review, at the Publication stage.', 1),
    (5, 'admin', 5, 'Manages users and role assignments; does not author documents.', 1);

INSERT INTO user_roles (user_id, role_id, created_by)
  VALUES (1, 5, 1);

-- 4 demo accounts, one per remaining role, "created by" the admin above -
-- same placeholder password "password", each with its own bcrypt salt.
INSERT INTO users (user_id, full_name, email, is_active, created_by)
  OVERRIDING SYSTEM VALUE
  VALUES
    (2, 'Aman Bisht', 'aman.bisht@docflow.author', true, 1),
    (3, 'Esha Singh', 'esha.singh@docflow.editor', true, 1),
    (4, 'Rita Kumari', 'rita.kumari@docflow.reviewer', true, 1),
    (5, 'Piyush Bhatt', 'piyush.bhatt@docflow.publisher', true, 1);

INSERT INTO user_passwords (user_id, hash_password, created_by)
  VALUES
    (2, '$2b$12$N2sYNzhOSeYSw4j2Vz0Y/uowuHT7Y8m5EZYCONFdpx/BKnMIa.s4G', 1),
    (3, '$2b$12$r76.TsruGD/nHk9erUxxSuJE0TQnR9s3A2rOIh6vjPEswrLwi9Z.C', 1),
    (4, '$2b$12$3c5qvhodERcD9a6d0zkoM.HHbNpVkOBxqqw1A.4HtHLxOWNRucC96', 1),
    (5, '$2b$12$dzyS6kZIb24jzOeuxPGhiONQJ8Blh6ZDpQUplsFcHryJzxbJAUT9.', 1);

INSERT INTO user_roles (user_id, role_id, created_by)
  VALUES
    (2, 1, 1), -- author
    (3, 2, 1), -- editor
    (4, 3, 1), -- reviewer
    (5, 4, 1); -- publisher
